<?php
$config = Zend_Registry::get('config');
$session = new Zend_Session_Namespace('game');
$board = new Model_Board();

?>

<p>Player number: <span id="player_num"><?php echo $session->player->player_num; ?></span></p>

<div class="actions">
    <span><a href="javascript:Game.sendCommand('roll_dice');">Roll Dice</a></span>

    <span><a href="javascript:Game.sendCommand('buy_property');">Buy Property</a></span>

    <span><a href="javascript:Game.sendCommand('use_goojf');">GOOJF</a></span>

    <span><a href="javascript:Game.sendCommand('end_turn');">End Turn</a></span>

</div>

<div class="clear"></div>

<table class="board">
<?php

echo '<tr><td></td>';
for ($i = 0; $i < $this->game->getPlayersPlaying(); $i++) {
    echo '<th class="player_' . $i . '">P' . $i . '</th>';
}
echo '<td style="width: 50px;"></td>';
echo '<th>Owned By</th>';
echo '<th>Houses / Hotel</th>';
echo '</tr>';

for ($i = 0; $i < Model_Game::MAX_POSITIONS; $i++) {
    $group = $board->getColourGroup($i);
    echo '<tr class="pos_' . $i . ' group_' . $group . '"><td>' . $board->getNameOf($i) . '</td>';

    for ($j = 0; $j < $this->game->getPlayersPlaying(); $j++) {
        echo '<td></td>';
    }
	echo '<td></td>';
	echo '<td class="ob' . $i. '"></td>';
	echo '<td class="hh' . $i. '"></td>';
    echo '</tr>';
}
?>

</table>

<table class="info">
	<tr>
		<th>Player</th>
        <th>Name</th>
		<th>Turn</th>
		<th>Money</th>
        <th>GOoJFC</th>
	</tr>
	<?php
	for ($i = 0; $i < $this->game->getPlayersPlaying(); $i++) {
		echo '<tr><td>' . $i . '</td>';
		echo '<td>' . $this->game->getPlayer($i)->name . '</td>';
		echo '<td class="player_turn turn_' . $i . '"></td>';
		echo '<td class="money_' . $i . '"></td>';
		echo '<td class="goojf_' . $i . '"></td></tr>';
	}
	?>
</table>

<div class="clear"></div>

<script type="text/javascript">
    Game.init();
</script>
