<?php
$config = Zend_Registry::get('config');
?>

<script type="text/javascript" src="/js/game.js"></script>
<script type="text/javascript" src="/js/board_uk.js"></script>

<script>
Game.init();
</script>

<?php
$session = new Zend_Session_Namespace('game');
?>
<p>Player number: <input id="player_num" value="<?php echo $session->player->player_num; ?>" />


<p><a href="javascript:Game.sendCommand('roll_dice');">Roll Dice</a></p>

<p><a href="javascript:Game.sendCommand('buy_property');">Buy Property</a></p>

<p><a href="javascript:Game.sendCommand('use_goojf');">GOOJF</a></p>

<p><a href="javascript:Game.sendCommand('end_turn');">End Turn</a></p>

<p><a href="javascript:Game.sendCommand('new_game');">New Game</a></p>

<table class="info" border="1">
	<tr>
		<td></td>
		<td class="player_name_0">Player 1</td>
		<td class="player_name_1">Player 2</td>
		<td class="player_name_2">Player 3</td>
	</tr>
	<tr>
		<td>On:</td>
		<td class="p0_on"></td>
		<td class="p1_on"></td>
		<td class="p2_on"></td>
	</tr>
</table>

<pre id="debug"></pre>