<?php
?>
<!DOCTYPE html>
<html>
	<head>
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
        <?php echo $this->headScript(); ?>

        <link type="text/css" rel="stylesheet" href="/css/screen.css?v=3" />
        <?php echo $this->headLink() ?>

		<title></title>
	</head>

	<body>
		<div id="frame">
			<div class="content">
				<?php echo $this->layout()->content ?>
			</div>

		</div>

	</body>
</html>